services:
  web:
    image: ${DOCKER_IMAGE_TAG}
    container_name: cdidoor-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env.local
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 80M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
